### ISSUE TITLE
Calage des filets sur les valeurs clés

### ISSUE THREAD

**Issue by odoutrellot** [etaminstudio/grandformat-paris2024#13]
Les filets devraient être alignés entre eux, prévoir retour à la ligne pour le titre du dessus au besoin
![capture d ecran 2017-09-14 a 16 03 09 1](https://user-images.githubusercontent.com/25613875/30434573-ef5ba3ea-9967-11e7-9a2b-bebd482f03db.png)

**Comment by Spone** [comment]
@acekat @gregossito attention ce commit modifie la structure de _data.json (à reporter côté front si nécessaire)
