### ISSUE TITLE
Le développement durable > Titre => Retour à la ligne entre Développement et durable sur le titre

### ISSUE THREAD

**Issue by odoutrellot** [etaminstudio/grandformat-paris2024#14]

**Comment by Spone** [comment]
@odoutrellot Pas compris ? Tu peux faire un screenshot ?

**Comment by odoutrellot** [comment]
Et voilà : 
![capture d ecran 2017-09-14 a 16 03 09 7](https://user-images.githubusercontent.com/25613875/30436306-1fbaef92-996c-11e7-827d-653ed3e13eb8.png)

**Comment by gregossito** [comment]
@spone il faut rajouter un max width sur le titre et un margin: 0 auto, on te le laisse pour pas se marcher sur les pieds
