### ISSUE TITLE
DD > Supprimer le bloc de citation

### ISSUE THREAD

**Issue by odoutrellot** [etaminstudio/grandformat-paris2024#18]
![capture d ecran 2017-09-14 a 16 03 09 5](https://user-images.githubusercontent.com/25613875/30435151-5835126a-9969-11e7-8ac9-19b84713269c.png)

**Comment by Spone** [comment]
C'est à dire ? On le supprime complètement ? Il ne sera utilisé sur aucune page ?

**Comment by odoutrellot** [comment]
Oui, pas d'usage sur cette page (et du coup dans le webdoc il me semble)

**Comment by Spone** [comment]
Ok donc je supprime le module aussi, s'il n'est plus utilisé.
