### ISSUE TITLE
Le placement des boules rouges + couleur

### ISSUE THREAD

**Issue by odoutrellot** [etaminstudio/grandformat-paris2024#21]
![capture d ecran 2017-09-14 a 16 03 09 6](https://user-images.githubusercontent.com/25613875/30435485-244e1ffe-996a-11e7-9173-25d8504d47f1.png)

Placement en triangle inversé plus couleur de fond des cercles qui ne sont pas les mêmes à chaque fois dans la maquette

**Comment by Spone** [comment]
@acekat @gregossito attention ce commit modifie la structure de `_data.json` (à reporter côté front si nécessaire)
