### ISSUE TITLE
Logo navbar

### ISSUE THREAD

**Issue by Spone** [etaminstudio/grandformat-paris2024#24]
@odoutrellot On fait quoi, ça reste comme ça ?

![image](https://user-images.githubusercontent.com/38524/30446931-da80c66c-998a-11e7-95f4-315f32324384.png)

**Comment by gregossito** [comment]
bonne question, je plussoie d'un emoji +1 :+1:

**Comment by gregossito** [comment]
@odoutrellot sera là vers 10H30, 11H, je vais tenter de récupérer l'info avant

**Comment by gregossito** [comment]
@spone on a effectivement un changement sur le logo car là il ne se voit pas en entier, il ne doit pas être croppé, normalement c'est du côté de Nico
