### ISSUE TITLE
Budget : Un projet qui utilise d’abord l’existant, pas de bandeau bleu

### ISSUE THREAD

**Issue by odoutrellot** [etaminstudio/grandformat-paris2024#6]
Dans la maquette c'était ça : 

![capture d ecran 2017-09-14 a 16 13 16](https://user-images.githubusercontent.com/25613875/30434450-a57143fc-9967-11e7-87f0-f2551dc2d436.png)

**Comment by Spone** [comment]
@acekat @gregossito attention ce commit modifie la structure de _data.json (à reporter côté front si nécessaire)
